#!/bin/bash
# thanks https://faq.i3wm.org/question/2332/flexible-monitor-setup.1.html

case $(hostname) in
  tom-pc )
    xrandr | grep ' connected' | grep -q VGA-0 && {
      echo 'Home PC with VGA'
      xrandr --output VGA-0 --auto --left-of DVI-I-1
      exit 0
    }
    echo 'Home PC with HDMI'
    xrandr --output LVDS1 --auto --left-of HDMI1
    ;;
  tom-w650eh )
    for output in $(xrandr | grep '\Wconnected' | awk '{ print $1 }'); do
      if [[ $output =~ ^LVDS.*$ ]]; then
        lvds=$output
      fi
    done
    for output in $(xrandr | grep '\Wconnected' | awk '{ print $1 }'); do
      if [[ ! $output =~ ^LVDS.*$ ]]; then
        echo 'W650EH using two external displays via HDMI + VGA'
        xrandr --output HDMI1 --auto --left-of VGA1 --output LVDS1 --off
        exit
      fi
    done
    echo 'W650EH using built-in display'
    xrandr --output $lvds --auto
    ;;
  tom-x1eg2 )
    for output in $(xrandr | grep '\Wconnected' | awk '{ print $1 }'); do
      if [[ $output =~ ^eDP.*$ ]]; then
        builtinDisplay=$output
      fi
    done
    connectedDisplays=$(xrandr \
      | grep '\Wconnected' \
      | awk '{ print $1 }' \
      | sort \
      | tr '\n' ' ')
    echo "Connected displays: $connectedDisplays"
    if [[ $connectedDisplays == 'eDP-1-1 HDMI-0 ' ]]; then
      echo 'Lenovo X1 Extreme Gen2: HDMI and laptop displays'
      xrandr \
        --output HDMI-0 --auto \
        --output eDP-1-1 --mode 1600x900 --left-of HDMI-0
      exit
    fi
    if [[ $connectedDisplays == 'DP-1 HDMI-0 ' ]]; then
      echo 'Lenovo X1 Extreme Gen2: HDMI + VGA displays'
        xrandr \
          --output HDMI-0 --auto \
          --output DP-1 --auto --right-of HDMI-0 \
          --output $builtinDisplay --off
          #--output $builtinDisplay --auto --below HDMI-0 # enables 3rd display
      exit
    fi
    if [[ $connectedDisplays == 'DP-0 eDP-1-1 ' ]]; then
      echo 'Lenovo X1 Extreme Gen2: DP + laptop displays'
        xrandr \
        --output DP-0 --mode 1680x1050 \
        --output eDP-1-1 --mode 1600x900 --left-of DP-0
      exit
    fi
    echo 'Lenovo X1 Extreme Gen2 using built-in display'
    xrandr \
      --output HDMI-0 --off \
      --output DP-0 --off \
      --output $builtinDisplay --auto
    ;;
  * )
    echo '[ERROR] unhandled hostname'
    exit 1
    ;;
esac
