#!/bin/bash
# thanks https://faq.i3wm.org/question/2332/flexible-monitor-setup.1.html

case $(hostname) in
  tom-pc )
    xrandr | grep ' connected' | grep -q VGA-0 && {
      echo 'Home PC with VGA'
      xrandr --output VGA-0 --auto --left-of DVI-I-1
      exit 0
    }
    echo 'Home PC with HDMI'
    xrandr --output LVDS1 --auto --left-of HDMI1
    ;;
  tom-w650eh )
    for output in $(xrandr | grep '\Wconnected' | awk '{ print $1 }'); do
      if [[ $output =~ ^LVDS.*$ ]]; then
        lvds=$output
      fi
    done
    for output in $(xrandr | grep '\Wconnected' | awk '{ print $1 }'); do
      if [[ ! $output =~ ^LVDS.*$ ]]; then
        echo 'W650EH using two external displays via HDMI + VGA'
        xrandr --output HDMI1 --auto --left-of VGA1 --output LVDS1 --off
        exit
      fi
    done
    echo 'W650EH using built-in display'
    xrandr --output $lvds --auto
    ;;
  tom-x1eg2 )
    for output in $(xrandr | grep '\Wconnected' | awk '{ print $1 }'); do
      if [[ $output =~ ^eDP.*$ ]]; then
        builtinDisplay=$output
      fi
    done
    for output in $(xrandr | grep '\Wconnected' | awk '{ print $1 }'); do
      if [[ ! $output =~ ^eDP.*$ ]]; then
        echo 'Lenovo X1 Extreme Gen2 using two external displays via HDMI + VGA'
        xrandr \
          --output HDMI-0 --auto \
          --output DP-1 --auto --right-of HDMI-0 \
          --output $builtinDisplay --off
          #--output $builtinDisplay --auto --below HDMI-0 # enables 3rd display
        exit
      fi
    done
    echo 'Lenovo X1 Extreme Gen2 using built-in display'
    xrandr \
      --output HDMI-0 --off \
      --output DP-0 --off \
      --output $builtinDisplay --auto
    ;;
  * )
    echo '[ERROR] unhandled hostname'
    exit 1
    ;;
esac
