#!/bin/bash
set -euo pipefail

# so we get the correct TZ value
source ~/.profile

/zeta/git/bumblebee-status/bumblebee-status \
    -m traffic docker_ps pacman disk load cpu memory sensors battery pasink datetime \
    -p \
      datetime.format="%Y-%m-%d %a %H:%M:%S" \
      disk.format="{percent:5.0f}%" \
      engine.workspacewrap=false \
      memory.format="{percent:5.0f}%" \
      sensors.json=true \
      sensors.path="coretemp-isa-0000/Package id 0/temp1_input" \
      traffic.exclude="tun,lo,vpn,docker,br" \
      traffic.graphlen=16 \
      traffic.showname=False \
      traffic.states="^down" \
      traffic.format="{:_>07.1f}" \
    -t gruvbox-tom
