#!/bin/bash
# toggle trackball cursor speed for precision movement
set -euo pipefail
signalFile=/tmp/mouse-precision
id="pointer:ELECOM TrackBall Mouse DEFT Pro TrackBall"
ctm=193 # Coordinate Transformation Matrix
ape=341 # Accel Profile Enabled

function doit {
  ctmVal=${1:?}
  apeVal=${2:?}
  # thanks https://bbs.archlinux.org/viewtopic.php?pid=1830611#p1830611
  xinput set-prop "$id" "$ctm" 1, 0, 0, 0, 1, 0, 0, 0, $ctmVal
  xinput set-prop "$id" "$ape" $apeVal, 0
}

if [ -f $signalFile ]; then
  echo "Toggling off"
  doit 1 1
  rm -f $signalFile
else
  echo "Toggling on"
  doit 60 0
  date > $signalFile
fi

xinput list-props "$id" | grep -e "$ctm" -e "$ape"
echo "Success"
