#!/bin/bash
# toggle trackball cursor speed for precision movement
set -euo pipefail
if [ ! -z "${DEBUG:-}" ]; then
  set -x
fi
signalFile=/tmp/mouse-precision
id="pointer:ELECOM TrackBall Mouse DEFT Pro TrackBall"
ctm='Coordinate Transformation Matrix'
ape='libinput Accel Profile Enabled'
asp='libinput Accel Speed'
overridePrecision=${1:-}
precision=${overridePrecision:-10}
# originally I turned acceleration off, but I think it adds accuracy
accelEnabledInPrecisionMode=1
accelSpeed=${2:-1}

function doit {
  ctmVal=${1:?}
  apeVal=${2:?}
  aspVal=${3:?}
  # thanks https://bbs.archlinux.org/viewtopic.php?pid=1830611#p1830611
  xinput set-prop "$id" "$ctm" 1, 0, 0, 0, 1, 0, 0, 0, $ctmVal
  xinput set-prop "$id" "$ape" $apeVal, 0
  xinput set-prop "$id" "$asp" $aspVal
}

if [ ! -f $signalFile -o ! -z "$overridePrecision" ]; then
  echo "Toggling on, with $precision"
  doit $precision $accelEnabledInPrecisionMode -1
  date > $signalFile
else
  echo "Toggling off"
  doit 2.5 1 $accelSpeed
  rm -f $signalFile
fi

xinput list-props "$id" | grep -e "$ctm" -e "$ape" -e $"$asp"
echo "Success"
